language: node_js
node_js:
- 0.10.26
notifications:
  irc: irc.freenode.org#generator-travis-ci
branches:
  only:
  - development
env:
  global:
  - GH_OWNER: Paden
  - GH_PROJECT_NAME: Paden.github.io
  - secure: Dln60P2A9NYY6OCpoWJ7ppXlOLhd79wkt8/2suFaJi1iiBoJmw3LO9AhjZuJDhcUn0ZJW1xtULIU04dmzH1McNrNV8yNnBpbuCkAF2xFOIv6KVtp/3ayhaJQYWbeH9nKhwAPHq0GBKuQ9iRCsq3VKrszRBfLc3pJoJt2DgM03G4=
before_script:
- gem update --system
- npm install -g grunt-cli bower
script:
- bower install
- grunt
after_success:
- git submodule add -b master https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME}
  site > /dev/null 2>&1
- cd site
- if git checkout master; then git checkout -b master; fi
- git rm -r .
- cp -R ../dist/* .
- cp ../dist/.* .
- git add -f .
- git config user.email "padenportillo.com"
- git config user.name "Paden Portillo"
- git commit -am "adding the yeoman build files to master [ci skip]"
- git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:master
  > /dev/null 2>&1
